# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/qxdzbc/p6/proto/rpc/workbook/WorkbooKServiceProtos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.qxdzbc.p6.proto import CommonProtos_pb2 as com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2
from com.qxdzbc.p6.proto import DocProtos_pb2 as com_dot_qxdzbc_dot_p6_dot_proto_dot_DocProtos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<com/qxdzbc/p6/proto/rpc/workbook/WorkbooKServiceProtos.proto\x12 com.qxdzbc.p6.proto.rpc.workbook\x1a&com/qxdzbc/p6/proto/CommonProtos.proto\x1a#com/qxdzbc/p6/proto/DocProtos.proto\"\x93\x01\n WorksheetWithErrorReportMsgProto\x12\x13\n\x06wsName\x18\x01 \x01(\tH\x00\x88\x01\x01\x12?\n\x0b\x65rrorReport\x18\x02 \x01(\x0b\x32%.com.qxdzbc.p6.proto.ErrorReportProtoH\x01\x88\x01\x01\x42\t\n\x07_wsNameB\x0e\n\x0c_errorReport\"\x85\x01\n\x14SetWbKeyRequestProto\x12\x34\n\x05wbKey\x18\x01 \x01(\x0b\x32%.com.qxdzbc.p6.proto.WorkbookKeyProto\x12\x37\n\x08newWbKey\x18\x02 \x01(\x0b\x32%.com.qxdzbc.p6.proto.WorkbookKeyProto\"u\n\x1bRenameWorksheetRequestProto\x12\x34\n\x05wbKey\x18\x01 \x01(\x0b\x32%.com.qxdzbc.p6.proto.WorkbookKeyProto\x12\x0f\n\x07oldName\x18\x02 \x01(\t\x12\x0f\n\x07newName\x18\x03 \x01(\t\"\x93\x01\n\x19IdentifyWorksheetMsgProto\x12\x34\n\x05wbKey\x18\x01 \x01(\x0b\x32%.com.qxdzbc.p6.proto.WorkbookKeyProto\x12\x13\n\x06wsName\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07wsIndex\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\t\n\x07_wsNameB\n\n\x08_wsIndex\"f\n\x19GetWorksheetResponseProto\x12;\n\tworksheet\x18\x01 \x01(\x0b\x32#.com.qxdzbc.p6.proto.WorksheetProtoH\x00\x88\x01\x01\x42\x0c\n\n_worksheet\"\xa9\x01\n\x1dGetAllWorksheetsResponseProto\x12\x37\n\nworksheets\x18\x01 \x03(\x0b\x32#.com.qxdzbc.p6.proto.WorksheetProto\x12?\n\x0b\x65rrorReport\x18\x02 \x01(\x0b\x32%.com.qxdzbc.p6.proto.ErrorReportProtoH\x00\x88\x01\x01\x42\x0e\n\x0c_errorReport\"\x8a\x01\n\x1e\x43reateNewWorksheetRequestProto\x12\x34\n\x05wbKey\x18\x01 \x01(\x0b\x32%.com.qxdzbc.p6.proto.WorkbookKeyProto\x12\x1d\n\x10newWorksheetName\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x13\n\x11_newWorksheetName\"\x88\x01\n\x18\x41\x64\x64WorksheetRequestProto\x12\x34\n\x05wbKey\x18\x01 \x01(\x0b\x32%.com.qxdzbc.p6.proto.WorkbookKeyProto\x12\x36\n\tworksheet\x18\x02 \x01(\x0b\x32#.com.qxdzbc.p6.proto.WorksheetProtob\x06proto3')



_WORKSHEETWITHERRORREPORTMSGPROTO = DESCRIPTOR.message_types_by_name['WorksheetWithErrorReportMsgProto']
_SETWBKEYREQUESTPROTO = DESCRIPTOR.message_types_by_name['SetWbKeyRequestProto']
_RENAMEWORKSHEETREQUESTPROTO = DESCRIPTOR.message_types_by_name['RenameWorksheetRequestProto']
_IDENTIFYWORKSHEETMSGPROTO = DESCRIPTOR.message_types_by_name['IdentifyWorksheetMsgProto']
_GETWORKSHEETRESPONSEPROTO = DESCRIPTOR.message_types_by_name['GetWorksheetResponseProto']
_GETALLWORKSHEETSRESPONSEPROTO = DESCRIPTOR.message_types_by_name['GetAllWorksheetsResponseProto']
_CREATENEWWORKSHEETREQUESTPROTO = DESCRIPTOR.message_types_by_name['CreateNewWorksheetRequestProto']
_ADDWORKSHEETREQUESTPROTO = DESCRIPTOR.message_types_by_name['AddWorksheetRequestProto']
WorksheetWithErrorReportMsgProto = _reflection.GeneratedProtocolMessageType('WorksheetWithErrorReportMsgProto', (_message.Message,), {
  'DESCRIPTOR' : _WORKSHEETWITHERRORREPORTMSGPROTO,
  '__module__' : 'com.qxdzbc.p6.proto.rpc.workbook.WorkbooKServiceProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.qxdzbc.p6.proto.rpc.workbook.WorksheetWithErrorReportMsgProto)
  })
_sym_db.RegisterMessage(WorksheetWithErrorReportMsgProto)

SetWbKeyRequestProto = _reflection.GeneratedProtocolMessageType('SetWbKeyRequestProto', (_message.Message,), {
  'DESCRIPTOR' : _SETWBKEYREQUESTPROTO,
  '__module__' : 'com.qxdzbc.p6.proto.rpc.workbook.WorkbooKServiceProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.qxdzbc.p6.proto.rpc.workbook.SetWbKeyRequestProto)
  })
_sym_db.RegisterMessage(SetWbKeyRequestProto)

RenameWorksheetRequestProto = _reflection.GeneratedProtocolMessageType('RenameWorksheetRequestProto', (_message.Message,), {
  'DESCRIPTOR' : _RENAMEWORKSHEETREQUESTPROTO,
  '__module__' : 'com.qxdzbc.p6.proto.rpc.workbook.WorkbooKServiceProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.qxdzbc.p6.proto.rpc.workbook.RenameWorksheetRequestProto)
  })
_sym_db.RegisterMessage(RenameWorksheetRequestProto)

IdentifyWorksheetMsgProto = _reflection.GeneratedProtocolMessageType('IdentifyWorksheetMsgProto', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFYWORKSHEETMSGPROTO,
  '__module__' : 'com.qxdzbc.p6.proto.rpc.workbook.WorkbooKServiceProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.qxdzbc.p6.proto.rpc.workbook.IdentifyWorksheetMsgProto)
  })
_sym_db.RegisterMessage(IdentifyWorksheetMsgProto)

GetWorksheetResponseProto = _reflection.GeneratedProtocolMessageType('GetWorksheetResponseProto', (_message.Message,), {
  'DESCRIPTOR' : _GETWORKSHEETRESPONSEPROTO,
  '__module__' : 'com.qxdzbc.p6.proto.rpc.workbook.WorkbooKServiceProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.qxdzbc.p6.proto.rpc.workbook.GetWorksheetResponseProto)
  })
_sym_db.RegisterMessage(GetWorksheetResponseProto)

GetAllWorksheetsResponseProto = _reflection.GeneratedProtocolMessageType('GetAllWorksheetsResponseProto', (_message.Message,), {
  'DESCRIPTOR' : _GETALLWORKSHEETSRESPONSEPROTO,
  '__module__' : 'com.qxdzbc.p6.proto.rpc.workbook.WorkbooKServiceProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.qxdzbc.p6.proto.rpc.workbook.GetAllWorksheetsResponseProto)
  })
_sym_db.RegisterMessage(GetAllWorksheetsResponseProto)

CreateNewWorksheetRequestProto = _reflection.GeneratedProtocolMessageType('CreateNewWorksheetRequestProto', (_message.Message,), {
  'DESCRIPTOR' : _CREATENEWWORKSHEETREQUESTPROTO,
  '__module__' : 'com.qxdzbc.p6.proto.rpc.workbook.WorkbooKServiceProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.qxdzbc.p6.proto.rpc.workbook.CreateNewWorksheetRequestProto)
  })
_sym_db.RegisterMessage(CreateNewWorksheetRequestProto)

AddWorksheetRequestProto = _reflection.GeneratedProtocolMessageType('AddWorksheetRequestProto', (_message.Message,), {
  'DESCRIPTOR' : _ADDWORKSHEETREQUESTPROTO,
  '__module__' : 'com.qxdzbc.p6.proto.rpc.workbook.WorkbooKServiceProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.qxdzbc.p6.proto.rpc.workbook.AddWorksheetRequestProto)
  })
_sym_db.RegisterMessage(AddWorksheetRequestProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORKSHEETWITHERRORREPORTMSGPROTO._serialized_start=176
  _WORKSHEETWITHERRORREPORTMSGPROTO._serialized_end=323
  _SETWBKEYREQUESTPROTO._serialized_start=326
  _SETWBKEYREQUESTPROTO._serialized_end=459
  _RENAMEWORKSHEETREQUESTPROTO._serialized_start=461
  _RENAMEWORKSHEETREQUESTPROTO._serialized_end=578
  _IDENTIFYWORKSHEETMSGPROTO._serialized_start=581
  _IDENTIFYWORKSHEETMSGPROTO._serialized_end=728
  _GETWORKSHEETRESPONSEPROTO._serialized_start=730
  _GETWORKSHEETRESPONSEPROTO._serialized_end=832
  _GETALLWORKSHEETSRESPONSEPROTO._serialized_start=835
  _GETALLWORKSHEETSRESPONSEPROTO._serialized_end=1004
  _CREATENEWWORKSHEETREQUESTPROTO._serialized_start=1007
  _CREATENEWWORKSHEETREQUESTPROTO._serialized_end=1145
  _ADDWORKSHEETREQUESTPROTO._serialized_start=1148
  _ADDWORKSHEETREQUESTPROTO._serialized_end=1284
# @@protoc_insertion_point(module_scope)
