from pysat.formula import CNF
from pysat.solvers import Glucose3

formula = CNF()
g = Glucose3(with_proof=True)
# g.add_clause([ -2, 28])
g.add_clause([ 2, -2, 7 ])
g.add_clause([ -1, -2, 7 ])
g.add_clause([ 2, 1, 7 ])
g.add_clause([ -1, 1, 7 ])
g.add_clause([ -2, 1, -7 ])
g.add_clause([ 2, -1, -7 ])
g.add_clause([ 4, -4, 8 ])
g.add_clause([ -3, -4, 8 ])
g.add_clause([ 4, 3, 8 ])
g.add_clause([ -3, 3, 8 ])
g.add_clause([ -4, 3, -8 ])
g.add_clause([ 4, -3, -8 ])
g.add_clause([ -8, -7, 6 ])
g.add_clause([ 8, -6 ])
g.add_clause([ 7, -6 ])
g.add_clause([ -3, 3, 5 ])
g.add_clause([ -6, 3, 5 ])
g.add_clause([ -3, 6, 5 ])
g.add_clause([ -6, 6, 5 ])
g.add_clause([ 3, 6, -5 ])
g.add_clause([ -3, -6, -5 ])
g.add_clause([ 5 ])

print(g.solve())