# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/qxdzbc/p6/proto/P6MsgProtos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%com/qxdzbc/p6/proto/P6MsgProtos.proto\x12\x13\x63om.qxdzbc.p6.proto\"*\n\x0cP6EventProto\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"[\n\x14P6MessageHeaderProto\x12\r\n\x05msgId\x18\x01 \x01(\t\x12\x34\n\teventType\x18\x02 \x01(\x0b\x32!.com.qxdzbc.p6.proto.P6EventProto\"Y\n\x0eP6MessageProto\x12\x39\n\x06header\x18\x01 \x01(\x0b\x32).com.qxdzbc.p6.proto.P6MessageHeaderProto\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\xc1\x01\n\x0fP6ResponseProto\x12\x39\n\x06header\x18\x01 \x01(\x0b\x32).com.qxdzbc.p6.proto.P6MessageHeaderProto\x12;\n\x06status\x18\x02 \x01(\x0e\x32+.com.qxdzbc.p6.proto.P6ResponseProto.Status\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"(\n\x06Status\x12\x0b\n\x07INVALID\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x62\x06proto3')



_P6EVENTPROTO = DESCRIPTOR.message_types_by_name['P6EventProto']
_P6MESSAGEHEADERPROTO = DESCRIPTOR.message_types_by_name['P6MessageHeaderProto']
_P6MESSAGEPROTO = DESCRIPTOR.message_types_by_name['P6MessageProto']
_P6RESPONSEPROTO = DESCRIPTOR.message_types_by_name['P6ResponseProto']
_P6RESPONSEPROTO_STATUS = _P6RESPONSEPROTO.enum_types_by_name['Status']
P6EventProto = _reflection.GeneratedProtocolMessageType('P6EventProto', (_message.Message,), {
  'DESCRIPTOR' : _P6EVENTPROTO,
  '__module__' : 'com.qxdzbc.p6.proto.P6MsgProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.qxdzbc.p6.proto.P6EventProto)
  })
_sym_db.RegisterMessage(P6EventProto)

P6MessageHeaderProto = _reflection.GeneratedProtocolMessageType('P6MessageHeaderProto', (_message.Message,), {
  'DESCRIPTOR' : _P6MESSAGEHEADERPROTO,
  '__module__' : 'com.qxdzbc.p6.proto.P6MsgProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.qxdzbc.p6.proto.P6MessageHeaderProto)
  })
_sym_db.RegisterMessage(P6MessageHeaderProto)

P6MessageProto = _reflection.GeneratedProtocolMessageType('P6MessageProto', (_message.Message,), {
  'DESCRIPTOR' : _P6MESSAGEPROTO,
  '__module__' : 'com.qxdzbc.p6.proto.P6MsgProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.qxdzbc.p6.proto.P6MessageProto)
  })
_sym_db.RegisterMessage(P6MessageProto)

P6ResponseProto = _reflection.GeneratedProtocolMessageType('P6ResponseProto', (_message.Message,), {
  'DESCRIPTOR' : _P6RESPONSEPROTO,
  '__module__' : 'com.qxdzbc.p6.proto.P6MsgProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.qxdzbc.p6.proto.P6ResponseProto)
  })
_sym_db.RegisterMessage(P6ResponseProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _P6EVENTPROTO._serialized_start=62
  _P6EVENTPROTO._serialized_end=104
  _P6MESSAGEHEADERPROTO._serialized_start=106
  _P6MESSAGEHEADERPROTO._serialized_end=197
  _P6MESSAGEPROTO._serialized_start=199
  _P6MESSAGEPROTO._serialized_end=288
  _P6RESPONSEPROTO._serialized_start=291
  _P6RESPONSEPROTO._serialized_end=484
  _P6RESPONSEPROTO_STATUS._serialized_start=444
  _P6RESPONSEPROTO_STATUS._serialized_end=484
# @@protoc_insertion_point(module_scope)
