# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from com.qxdzbc.p6.proto import AppProtos_pb2 as com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2
from com.qxdzbc.p6.proto import CommonProtos_pb2 as com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2
from com.qxdzbc.p6.proto import DocProtos_pb2 as com_dot_qxdzbc_dot_p6_dot_proto_dot_DocProtos__pb2
from com.qxdzbc.p6.proto import WorksheetProtos_pb2 as com_dot_qxdzbc_dot_p6_dot_proto_dot_WorksheetProtos__pb2


class AppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getWorkbook = channel.unary_unary(
                '/com.qxdzbc.p6.proto.rpc.AppService/getWorkbook',
                request_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.GetWorkbookRequestProto.SerializeToString,
                response_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.WorkbookKeyWithErrorResponseProto.FromString,
                )
        self.createNewWorkbook = channel.unary_unary(
                '/com.qxdzbc.p6.proto.rpc.AppService/createNewWorkbook',
                request_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.CreateNewWorkbookRequestProto.SerializeToString,
                response_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.CreateNewWorkbookResponseProto.FromString,
                )
        self.getActiveWorkbook = channel.unary_unary(
                '/com.qxdzbc.p6.proto.rpc.AppService/getActiveWorkbook',
                request_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.EmptyProto.SerializeToString,
                response_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.WorkbookKeyWithErrorResponseProto.FromString,
                )
        self.setActiveWorkbook = channel.unary_unary(
                '/com.qxdzbc.p6.proto.rpc.AppService/setActiveWorkbook',
                request_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_DocProtos__pb2.WorkbookKeyProto.SerializeToString,
                response_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.SingleSignalResponseProto.FromString,
                )
        self.getActiveWorksheet = channel.unary_unary(
                '/com.qxdzbc.p6.proto.rpc.AppService/getActiveWorksheet',
                request_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.EmptyProto.SerializeToString,
                response_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_WorksheetProtos__pb2.GetWorksheetResponseProto.FromString,
                )
        self.saveWorkbookAtPath = channel.unary_unary(
                '/com.qxdzbc.p6.proto.rpc.AppService/saveWorkbookAtPath',
                request_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.SaveWorkbookRequestProto.SerializeToString,
                response_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.SaveWorkbookResponseProto.FromString,
                )
        self.loadWorkbook = channel.unary_unary(
                '/com.qxdzbc.p6.proto.rpc.AppService/loadWorkbook',
                request_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.LoadWorkbookRequestProto.SerializeToString,
                response_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.LoadWorkbookResponseProto.FromString,
                )
        self.closeWorkbook = channel.unary_unary(
                '/com.qxdzbc.p6.proto.rpc.AppService/closeWorkbook',
                request_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_DocProtos__pb2.WorkbookKeyProto.SerializeToString,
                response_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.SingleSignalResponseProto.FromString,
                )
        self.checkWbExistence = channel.unary_unary(
                '/com.qxdzbc.p6.proto.rpc.AppService/checkWbExistence',
                request_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_DocProtos__pb2.WorkbookKeyProto.SerializeToString,
                response_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.BoolMsgProto.FromString,
                )
        self.getAllWorkbooks = channel.unary_unary(
                '/com.qxdzbc.p6.proto.rpc.AppService/getAllWorkbooks',
                request_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.EmptyProto.SerializeToString,
                response_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.GetAllWorkbookResponseProto.FromString,
                )


class AppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getWorkbook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createNewWorkbook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getActiveWorkbook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setActiveWorkbook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getActiveWorksheet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def saveWorkbookAtPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def loadWorkbook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def closeWorkbook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkWbExistence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAllWorkbooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getWorkbook': grpc.unary_unary_rpc_method_handler(
                    servicer.getWorkbook,
                    request_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.GetWorkbookRequestProto.FromString,
                    response_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.WorkbookKeyWithErrorResponseProto.SerializeToString,
            ),
            'createNewWorkbook': grpc.unary_unary_rpc_method_handler(
                    servicer.createNewWorkbook,
                    request_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.CreateNewWorkbookRequestProto.FromString,
                    response_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.CreateNewWorkbookResponseProto.SerializeToString,
            ),
            'getActiveWorkbook': grpc.unary_unary_rpc_method_handler(
                    servicer.getActiveWorkbook,
                    request_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.EmptyProto.FromString,
                    response_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.WorkbookKeyWithErrorResponseProto.SerializeToString,
            ),
            'setActiveWorkbook': grpc.unary_unary_rpc_method_handler(
                    servicer.setActiveWorkbook,
                    request_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_DocProtos__pb2.WorkbookKeyProto.FromString,
                    response_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.SingleSignalResponseProto.SerializeToString,
            ),
            'getActiveWorksheet': grpc.unary_unary_rpc_method_handler(
                    servicer.getActiveWorksheet,
                    request_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.EmptyProto.FromString,
                    response_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_WorksheetProtos__pb2.GetWorksheetResponseProto.SerializeToString,
            ),
            'saveWorkbookAtPath': grpc.unary_unary_rpc_method_handler(
                    servicer.saveWorkbookAtPath,
                    request_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.SaveWorkbookRequestProto.FromString,
                    response_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.SaveWorkbookResponseProto.SerializeToString,
            ),
            'loadWorkbook': grpc.unary_unary_rpc_method_handler(
                    servicer.loadWorkbook,
                    request_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.LoadWorkbookRequestProto.FromString,
                    response_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.LoadWorkbookResponseProto.SerializeToString,
            ),
            'closeWorkbook': grpc.unary_unary_rpc_method_handler(
                    servicer.closeWorkbook,
                    request_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_DocProtos__pb2.WorkbookKeyProto.FromString,
                    response_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.SingleSignalResponseProto.SerializeToString,
            ),
            'checkWbExistence': grpc.unary_unary_rpc_method_handler(
                    servicer.checkWbExistence,
                    request_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_DocProtos__pb2.WorkbookKeyProto.FromString,
                    response_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.BoolMsgProto.SerializeToString,
            ),
            'getAllWorkbooks': grpc.unary_unary_rpc_method_handler(
                    servicer.getAllWorkbooks,
                    request_deserializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.EmptyProto.FromString,
                    response_serializer=com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.GetAllWorkbookResponseProto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.qxdzbc.p6.proto.rpc.AppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getWorkbook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.qxdzbc.p6.proto.rpc.AppService/getWorkbook',
            com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.GetWorkbookRequestProto.SerializeToString,
            com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.WorkbookKeyWithErrorResponseProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createNewWorkbook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.qxdzbc.p6.proto.rpc.AppService/createNewWorkbook',
            com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.CreateNewWorkbookRequestProto.SerializeToString,
            com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.CreateNewWorkbookResponseProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getActiveWorkbook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.qxdzbc.p6.proto.rpc.AppService/getActiveWorkbook',
            com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.EmptyProto.SerializeToString,
            com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.WorkbookKeyWithErrorResponseProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def setActiveWorkbook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.qxdzbc.p6.proto.rpc.AppService/setActiveWorkbook',
            com_dot_qxdzbc_dot_p6_dot_proto_dot_DocProtos__pb2.WorkbookKeyProto.SerializeToString,
            com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.SingleSignalResponseProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getActiveWorksheet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.qxdzbc.p6.proto.rpc.AppService/getActiveWorksheet',
            com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.EmptyProto.SerializeToString,
            com_dot_qxdzbc_dot_p6_dot_proto_dot_WorksheetProtos__pb2.GetWorksheetResponseProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def saveWorkbookAtPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.qxdzbc.p6.proto.rpc.AppService/saveWorkbookAtPath',
            com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.SaveWorkbookRequestProto.SerializeToString,
            com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.SaveWorkbookResponseProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def loadWorkbook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.qxdzbc.p6.proto.rpc.AppService/loadWorkbook',
            com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.LoadWorkbookRequestProto.SerializeToString,
            com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.LoadWorkbookResponseProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def closeWorkbook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.qxdzbc.p6.proto.rpc.AppService/closeWorkbook',
            com_dot_qxdzbc_dot_p6_dot_proto_dot_DocProtos__pb2.WorkbookKeyProto.SerializeToString,
            com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.SingleSignalResponseProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def checkWbExistence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.qxdzbc.p6.proto.rpc.AppService/checkWbExistence',
            com_dot_qxdzbc_dot_p6_dot_proto_dot_DocProtos__pb2.WorkbookKeyProto.SerializeToString,
            com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.BoolMsgProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAllWorkbooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.qxdzbc.p6.proto.rpc.AppService/getAllWorkbooks',
            com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2.EmptyProto.SerializeToString,
            com_dot_qxdzbc_dot_p6_dot_proto_dot_AppProtos__pb2.GetAllWorkbookResponseProto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
