# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/qxdzbc/p6/proto/rpc/app/AppServiceProtos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.qxdzbc.p6.proto import CommonProtos_pb2 as com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2
from com.qxdzbc.p6.proto import DocProtos_pb2 as com_dot_qxdzbc_dot_p6_dot_proto_dot_DocProtos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2com/qxdzbc/p6/proto/rpc/app/AppServiceProtos.proto\x12\x1b\x63om.qxdzbc.p6.proto.rpc.app\x1a&com/qxdzbc/p6/proto/CommonProtos.proto\x1a#com/qxdzbc/p6/proto/DocProtos.proto\"\xa0\x01\n\x17GetWorkbookRequestProto\x12\x39\n\x05wbKey\x18\x01 \x01(\x0b\x32%.com.qxdzbc.p6.proto.WorkbookKeyProtoH\x00\x88\x01\x01\x12\x13\n\x06wbName\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07wbIndex\x18\x03 \x01(\x03H\x02\x88\x01\x01\x42\x08\n\x06_wbKeyB\t\n\x07_wbNameB\n\n\x08_wbIndex\"\xb9\x01\n!WorkbookKeyWithErrorResponseProto\x12\x39\n\x05wbKey\x18\x01 \x01(\x0b\x32%.com.qxdzbc.p6.proto.WorkbookKeyProtoH\x00\x88\x01\x01\x12?\n\x0b\x65rrorReport\x18\x02 \x01(\x0b\x32%.com.qxdzbc.p6.proto.ErrorReportProtoH\x01\x88\x01\x01\x42\x08\n\x06_wbKeyB\x0e\n\x0c_errorReportb\x06proto3')



_GETWORKBOOKREQUESTPROTO = DESCRIPTOR.message_types_by_name['GetWorkbookRequestProto']
_WORKBOOKKEYWITHERRORRESPONSEPROTO = DESCRIPTOR.message_types_by_name['WorkbookKeyWithErrorResponseProto']
GetWorkbookRequestProto = _reflection.GeneratedProtocolMessageType('GetWorkbookRequestProto', (_message.Message,), {
  'DESCRIPTOR' : _GETWORKBOOKREQUESTPROTO,
  '__module__' : 'com.qxdzbc.p6.proto.rpc.app.AppServiceProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.qxdzbc.p6.proto.rpc.app.GetWorkbookRequestProto)
  })
_sym_db.RegisterMessage(GetWorkbookRequestProto)

WorkbookKeyWithErrorResponseProto = _reflection.GeneratedProtocolMessageType('WorkbookKeyWithErrorResponseProto', (_message.Message,), {
  'DESCRIPTOR' : _WORKBOOKKEYWITHERRORRESPONSEPROTO,
  '__module__' : 'com.qxdzbc.p6.proto.rpc.app.AppServiceProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.qxdzbc.p6.proto.rpc.app.WorkbookKeyWithErrorResponseProto)
  })
_sym_db.RegisterMessage(WorkbookKeyWithErrorResponseProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETWORKBOOKREQUESTPROTO._serialized_start=161
  _GETWORKBOOKREQUESTPROTO._serialized_end=321
  _WORKBOOKKEYWITHERRORRESPONSEPROTO._serialized_start=324
  _WORKBOOKKEYWITHERRORRESPONSEPROTO._serialized_end=509
# @@protoc_insertion_point(module_scope)
