# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/emeraldblast/p6/proto/rpc/cell/service/CellService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.emeraldblast.p6.proto.rpc.cell import GetCell_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_rpc_dot_cell_dot_GetCell__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<com/emeraldblast/p6/proto/rpc/cell/service/CellService.proto\x12*com.emeraldblast.p6.proto.rpc.cell.service\x1a\x30\x63om/emeraldblast/p6/proto/rpc/cell/GetCell.proto2\x88\x01\n\x0b\x43\x65llService\x12y\n\x0cgetCellValue\x12\x32.com.emeraldblast.p6.proto.rpc.cell.GetCellRequest\x1a\x33.com.emeraldblast.p6.proto.rpc.cell.GetCellResponse\"\x00\x62\x06proto3')



_CELLSERVICE = DESCRIPTOR.services_by_name['CellService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CELLSERVICE._serialized_start=159
  _CELLSERVICE._serialized_end=295
# @@protoc_insertion_point(module_scope)
