# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/qxdzbc/p6/proto/rpc/app/service/AppService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.qxdzbc.p6.proto import CommonProtos_pb2 as com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2
from com.qxdzbc.p6.proto import DocProtos_pb2 as com_dot_qxdzbc_dot_p6_dot_proto_dot_DocProtos__pb2
from com.qxdzbc.p6.proto.rpc.app import AppServiceProtos_pb2 as com_dot_qxdzbc_dot_p6_dot_proto_dot_rpc_dot_app_dot_AppServiceProtos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4com/qxdzbc/p6/proto/rpc/app/service/AppService.proto\x12#com.qxdzbc.p6.proto.rpc.app.service\x1a&com/qxdzbc/p6/proto/CommonProtos.proto\x1a#com/qxdzbc/p6/proto/DocProtos.proto\x1a\x32\x63om/qxdzbc/p6/proto/rpc/app/AppServiceProtos.proto2\x94\x01\n\nAppService\x12\x85\x01\n\x0bgetWorkbook\x12\x34.com.qxdzbc.p6.proto.rpc.app.GetWorkbookRequestProto\x1a>.com.qxdzbc.p6.proto.rpc.app.WorkbookKeyWithErrorResponseProto\"\x00\x62\x06proto3')



_APPSERVICE = DESCRIPTOR.services_by_name['AppService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _APPSERVICE._serialized_start=223
  _APPSERVICE._serialized_end=371
# @@protoc_insertion_point(module_scope)
