# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/emeraldblast/p6/proto/service/workbook/GetActiveWorksheetResponseProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.emeraldblast.p6.proto import CommonProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_CommonProtos__pb2
from com.emeraldblast.p6.proto import DocProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_DocProtos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nPcom/emeraldblast/p6/proto/service/workbook/GetActiveWorksheetResponseProto.proto\x12*com.emeraldblast.p6.proto.service.workbook\x1a,com/emeraldblast/p6/proto/CommonProtos.proto\x1a)com/emeraldblast/p6/proto/DocProtos.proto\"r\n\x1fGetActiveWorksheetResponseProto\x12\x41\n\tworksheet\x18\x01 \x01(\x0b\x32).com.emeraldblast.p6.proto.WorksheetProtoH\x00\x88\x01\x01\x42\x0c\n\n_worksheetb\x06proto3')



_GETACTIVEWORKSHEETRESPONSEPROTO = DESCRIPTOR.message_types_by_name['GetActiveWorksheetResponseProto']
GetActiveWorksheetResponseProto = _reflection.GeneratedProtocolMessageType('GetActiveWorksheetResponseProto', (_message.Message,), {
  'DESCRIPTOR' : _GETACTIVEWORKSHEETRESPONSEPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.service.workbook.GetActiveWorksheetResponseProto_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.service.workbook.GetActiveWorksheetResponseProto)
  })
_sym_db.RegisterMessage(GetActiveWorksheetResponseProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETACTIVEWORKSHEETRESPONSEPROTO._serialized_start=217
  _GETACTIVEWORKSHEETRESPONSEPROTO._serialized_end=331
# @@protoc_insertion_point(module_scope)
