# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/emeraldblast/p6/proto/service/workbook/GetWorksheetResponseProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.emeraldblast.p6.proto import CommonProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_CommonProtos__pb2
from com.emeraldblast.p6.proto import DocProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_DocProtos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJcom/emeraldblast/p6/proto/service/workbook/GetWorksheetResponseProto.proto\x12*com.emeraldblast.p6.proto.service.workbook\x1a,com/emeraldblast/p6/proto/CommonProtos.proto\x1a)com/emeraldblast/p6/proto/DocProtos.proto\"l\n\x19GetWorksheetResponseProto\x12\x41\n\tworksheet\x18\x01 \x01(\x0b\x32).com.emeraldblast.p6.proto.WorksheetProtoH\x00\x88\x01\x01\x42\x0c\n\n_worksheetb\x06proto3')



_GETWORKSHEETRESPONSEPROTO = DESCRIPTOR.message_types_by_name['GetWorksheetResponseProto']
GetWorksheetResponseProto = _reflection.GeneratedProtocolMessageType('GetWorksheetResponseProto', (_message.Message,), {
  'DESCRIPTOR' : _GETWORKSHEETRESPONSEPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.service.workbook.GetWorksheetResponseProto_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.service.workbook.GetWorksheetResponseProto)
  })
_sym_db.RegisterMessage(GetWorksheetResponseProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETWORKSHEETRESPONSEPROTO._serialized_start=211
  _GETWORKSHEETRESPONSEPROTO._serialized_end=319
# @@protoc_insertion_point(module_scope)
