# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/emeraldblast/p6/proto/service/workbook/IdentifyWorksheetMsgProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.emeraldblast.p6.proto import CommonProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_CommonProtos__pb2
from com.emeraldblast.p6.proto import DocProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_DocProtos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJcom/emeraldblast/p6/proto/service/workbook/IdentifyWorksheetMsgProto.proto\x12*com.emeraldblast.p6.proto.service.workbook\x1a,com/emeraldblast/p6/proto/CommonProtos.proto\x1a)com/emeraldblast/p6/proto/DocProtos.proto\"\x95\x01\n\x19IdentifyWorksheetMsgProto\x12:\n\x05wbKey\x18\x01 \x01(\x0b\x32+.com.emeraldblast.p6.proto.WorkbookKeyProto\x12\x13\n\x06wsName\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05index\x18\x03 \x01(\x03H\x01\x88\x01\x01\x42\t\n\x07_wsNameB\x08\n\x06_indexb\x06proto3')



_IDENTIFYWORKSHEETMSGPROTO = DESCRIPTOR.message_types_by_name['IdentifyWorksheetMsgProto']
IdentifyWorksheetMsgProto = _reflection.GeneratedProtocolMessageType('IdentifyWorksheetMsgProto', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFYWORKSHEETMSGPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.service.workbook.IdentifyWorksheetMsgProto_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.service.workbook.IdentifyWorksheetMsgProto)
  })
_sym_db.RegisterMessage(IdentifyWorksheetMsgProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IDENTIFYWORKSHEETMSGPROTO._serialized_start=212
  _IDENTIFYWORKSHEETMSGPROTO._serialized_end=361
# @@protoc_insertion_point(module_scope)
