# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/emeraldblast/p6/proto/service/workbook/WorkbookService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.emeraldblast.p6.proto import CommonProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_CommonProtos__pb2
from com.emeraldblast.p6.proto import DocProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_DocProtos__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from com.emeraldblast.p6.proto.service.workbook import SetWbName_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_service_dot_workbook_dot_SetWbName__pb2
from com.emeraldblast.p6.proto.service.workbook import GetAllWorksheets_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_service_dot_workbook_dot_GetAllWorksheets__pb2
from com.emeraldblast.p6.proto.service.workbook import IdentifyWorksheetMsgProto_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_service_dot_workbook_dot_IdentifyWorksheetMsgProto__pb2
from com.emeraldblast.p6.proto.service.workbook import GetWorksheetResponseProto_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_service_dot_workbook_dot_GetWorksheetResponseProto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@com/emeraldblast/p6/proto/service/workbook/WorkbookService.proto\x12*com.emeraldblast.p6.proto.service.workbook\x1a,com/emeraldblast/p6/proto/CommonProtos.proto\x1a)com/emeraldblast/p6/proto/DocProtos.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a:com/emeraldblast/p6/proto/service/workbook/SetWbName.proto\x1a\x41\x63om/emeraldblast/p6/proto/service/workbook/GetAllWorksheets.proto\x1aJcom/emeraldblast/p6/proto/service/workbook/IdentifyWorksheetMsgProto.proto\x1aJcom/emeraldblast/p6/proto/service/workbook/GetWorksheetResponseProto.proto2\xc9\x06\n\x0fWorkbookService\x12X\n\nsheetCount\x12+.com.emeraldblast.p6.proto.WorkbookKeyProto\x1a\x1b.google.protobuf.Int64Value\"\x00\x12\x86\x01\n\tsetWbName\x12\x41.com.emeraldblast.p6.proto.service.workbook.SetWbNameRequestProto\x1a\x34.com.emeraldblast.p6.proto.SingleSignalResponseProto\"\x00\x12\x8c\x01\n\x10getAllWorksheets\x12+.com.emeraldblast.p6.proto.WorkbookKeyProto\x1aI.com.emeraldblast.p6.proto.service.workbook.GetAllWorksheetsResponseProto\"\x00\x12\x95\x01\n\x14setActiveWorksheetRs\x12\x45.com.emeraldblast.p6.proto.service.workbook.IdentifyWorksheetMsgProto\x1a\x34.com.emeraldblast.p6.proto.SingleSignalResponseProto\"\x00\x12\x8a\x01\n\x12getActiveWorksheet\x12+.com.emeraldblast.p6.proto.WorkbookKeyProto\x1a\x45.com.emeraldblast.p6.proto.service.workbook.GetWorksheetResponseProto\"\x00\x12\x9e\x01\n\x0cgetWorksheet\x12\x45.com.emeraldblast.p6.proto.service.workbook.IdentifyWorksheetMsgProto\x1a\x45.com.emeraldblast.p6.proto.service.workbook.GetWorksheetResponseProto\"\x00\x62\x06proto3')



_WORKBOOKSERVICE = DESCRIPTOR.services_by_name['WorkbookService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORKBOOKSERVICE._serialized_start=542
  _WORKBOOKSERVICE._serialized_end=1383
# @@protoc_insertion_point(module_scope)
