# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/emeraldblast/p6/proto/rpc/workbook/AddWorksheetRequestProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.emeraldblast.p6.proto import CommonProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_CommonProtos__pb2
from com.emeraldblast.p6.proto import DocProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_DocProtos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEcom/emeraldblast/p6/proto/rpc/workbook/AddWorksheetRequestProto.proto\x12&com.emeraldblast.p6.proto.rpc.workbook\x1a,com/emeraldblast/p6/proto/CommonProtos.proto\x1a)com/emeraldblast/p6/proto/DocProtos.proto\"\x94\x01\n\x18\x41\x64\x64WorksheetRequestProto\x12:\n\x05wbKey\x18\x01 \x01(\x0b\x32+.com.emeraldblast.p6.proto.WorkbookKeyProto\x12<\n\tworksheet\x18\x02 \x01(\x0b\x32).com.emeraldblast.p6.proto.WorksheetProtob\x06proto3')



_ADDWORKSHEETREQUESTPROTO = DESCRIPTOR.message_types_by_name['AddWorksheetRequestProto']
AddWorksheetRequestProto = _reflection.GeneratedProtocolMessageType('AddWorksheetRequestProto', (_message.Message,), {
  'DESCRIPTOR' : _ADDWORKSHEETREQUESTPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.rpc.workbook.AddWorksheetRequestProto_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.rpc.workbook.AddWorksheetRequestProto)
  })
_sym_db.RegisterMessage(AddWorksheetRequestProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDWORKSHEETREQUESTPROTO._serialized_start=203
  _ADDWORKSHEETREQUESTPROTO._serialized_end=351
# @@protoc_insertion_point(module_scope)
