# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/emeraldblast/p6/proto/rpc/workbook/RenameWorksheetRequestProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.emeraldblast.p6.proto import CommonProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_CommonProtos__pb2
from com.emeraldblast.p6.proto import DocProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_DocProtos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHcom/emeraldblast/p6/proto/rpc/workbook/RenameWorksheetRequestProto.proto\x12&com.emeraldblast.p6.proto.rpc.workbook\x1a,com/emeraldblast/p6/proto/CommonProtos.proto\x1a)com/emeraldblast/p6/proto/DocProtos.proto\"{\n\x1bRenameWorksheetRequestProto\x12:\n\x05wbKey\x18\x01 \x01(\x0b\x32+.com.emeraldblast.p6.proto.WorkbookKeyProto\x12\x0f\n\x07oldName\x18\x02 \x01(\t\x12\x0f\n\x07newName\x18\x03 \x01(\tb\x06proto3')



_RENAMEWORKSHEETREQUESTPROTO = DESCRIPTOR.message_types_by_name['RenameWorksheetRequestProto']
RenameWorksheetRequestProto = _reflection.GeneratedProtocolMessageType('RenameWorksheetRequestProto', (_message.Message,), {
  'DESCRIPTOR' : _RENAMEWORKSHEETREQUESTPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.rpc.workbook.RenameWorksheetRequestProto_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.rpc.workbook.RenameWorksheetRequestProto)
  })
_sym_db.RegisterMessage(RenameWorksheetRequestProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RENAMEWORKSHEETREQUESTPROTO._serialized_start=205
  _RENAMEWORKSHEETREQUESTPROTO._serialized_end=328
# @@protoc_insertion_point(module_scope)
