# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/emeraldblast/p6/proto/rpc/workbook/WorksheetWithErrorReportMsgProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.emeraldblast.p6.proto import CommonProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_CommonProtos__pb2
from com.emeraldblast.p6.proto import DocProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_DocProtos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nMcom/emeraldblast/p6/proto/rpc/workbook/WorksheetWithErrorReportMsgProto.proto\x12&com.emeraldblast.p6.proto.rpc.workbook\x1a,com/emeraldblast/p6/proto/CommonProtos.proto\x1a)com/emeraldblast/p6/proto/DocProtos.proto\"\xca\x01\n WorksheetWithErrorReportMsgProto\x12\x41\n\tworksheet\x18\x01 \x01(\x0b\x32).com.emeraldblast.p6.proto.WorksheetProtoH\x00\x88\x01\x01\x12\x45\n\x0b\x65rrorReport\x18\x02 \x01(\x0b\x32+.com.emeraldblast.p6.proto.ErrorReportProtoH\x01\x88\x01\x01\x42\x0c\n\n_worksheetB\x0e\n\x0c_errorReportb\x06proto3')



_WORKSHEETWITHERRORREPORTMSGPROTO = DESCRIPTOR.message_types_by_name['WorksheetWithErrorReportMsgProto']
WorksheetWithErrorReportMsgProto = _reflection.GeneratedProtocolMessageType('WorksheetWithErrorReportMsgProto', (_message.Message,), {
  'DESCRIPTOR' : _WORKSHEETWITHERRORREPORTMSGPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.rpc.workbook.WorksheetWithErrorReportMsgProto_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.rpc.workbook.WorksheetWithErrorReportMsgProto)
  })
_sym_db.RegisterMessage(WorksheetWithErrorReportMsgProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORKSHEETWITHERRORREPORTMSGPROTO._serialized_start=211
  _WORKSHEETWITHERRORREPORTMSGPROTO._serialized_end=413
# @@protoc_insertion_point(module_scope)
