# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/emeraldblast/p6/proto/AppEventProtos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.emeraldblast.p6.proto import CommonProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_CommonProtos__pb2
from com.emeraldblast.p6.proto import DocProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_DocProtos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.com/emeraldblast/p6/proto/AppEventProtos.proto\x12\x19\x63om.emeraldblast.p6.proto\x1a,com/emeraldblast/p6/proto/CommonProtos.proto\x1a)com/emeraldblast/p6/proto/DocProtos.proto\"y\n\x1eSetActiveWorksheetRequestProto\x12@\n\x0bworkbookKey\x18\x01 \x01(\x0b\x32+.com.emeraldblast.p6.proto.WorkbookKeyProto\x12\x15\n\rworksheetName\x18\x02 \x01(\t\"\xcd\x01\n\x1fSetActiveWorksheetResponseProto\x12@\n\x0bworkbookKey\x18\x01 \x01(\x0b\x32+.com.emeraldblast.p6.proto.WorkbookKeyProto\x12\x15\n\rworksheetName\x18\x02 \x01(\t\x12\x0f\n\x07isError\x18\x03 \x01(\x08\x12@\n\x0b\x65rrorReport\x18\x04 \x01(\x0b\x32+.com.emeraldblast.p6.proto.ErrorReportProto\"(\n\x18LoadWorkbookRequestProto\x12\x0c\n\x04path\x18\x01 \x01(\t\"\xaa\x01\n\x19LoadWorkbookResponseProto\x12\x0f\n\x07isError\x18\x01 \x01(\x08\x12@\n\x0b\x65rrorReport\x18\x02 \x01(\x0b\x32+.com.emeraldblast.p6.proto.ErrorReportProto\x12:\n\x08workbook\x18\x03 \x01(\x0b\x32(.com.emeraldblast.p6.proto.WorkbookProtob\x06proto3')



_SETACTIVEWORKSHEETREQUESTPROTO = DESCRIPTOR.message_types_by_name['SetActiveWorksheetRequestProto']
_SETACTIVEWORKSHEETRESPONSEPROTO = DESCRIPTOR.message_types_by_name['SetActiveWorksheetResponseProto']
_LOADWORKBOOKREQUESTPROTO = DESCRIPTOR.message_types_by_name['LoadWorkbookRequestProto']
_LOADWORKBOOKRESPONSEPROTO = DESCRIPTOR.message_types_by_name['LoadWorkbookResponseProto']
SetActiveWorksheetRequestProto = _reflection.GeneratedProtocolMessageType('SetActiveWorksheetRequestProto', (_message.Message,), {
  'DESCRIPTOR' : _SETACTIVEWORKSHEETREQUESTPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.AppEventProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.SetActiveWorksheetRequestProto)
  })
_sym_db.RegisterMessage(SetActiveWorksheetRequestProto)

SetActiveWorksheetResponseProto = _reflection.GeneratedProtocolMessageType('SetActiveWorksheetResponseProto', (_message.Message,), {
  'DESCRIPTOR' : _SETACTIVEWORKSHEETRESPONSEPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.AppEventProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.SetActiveWorksheetResponseProto)
  })
_sym_db.RegisterMessage(SetActiveWorksheetResponseProto)

LoadWorkbookRequestProto = _reflection.GeneratedProtocolMessageType('LoadWorkbookRequestProto', (_message.Message,), {
  'DESCRIPTOR' : _LOADWORKBOOKREQUESTPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.AppEventProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.LoadWorkbookRequestProto)
  })
_sym_db.RegisterMessage(LoadWorkbookRequestProto)

LoadWorkbookResponseProto = _reflection.GeneratedProtocolMessageType('LoadWorkbookResponseProto', (_message.Message,), {
  'DESCRIPTOR' : _LOADWORKBOOKRESPONSEPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.AppEventProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.LoadWorkbookResponseProto)
  })
_sym_db.RegisterMessage(LoadWorkbookResponseProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETACTIVEWORKSHEETREQUESTPROTO._serialized_start=166
  _SETACTIVEWORKSHEETREQUESTPROTO._serialized_end=287
  _SETACTIVEWORKSHEETRESPONSEPROTO._serialized_start=290
  _SETACTIVEWORKSHEETRESPONSEPROTO._serialized_end=495
  _LOADWORKBOOKREQUESTPROTO._serialized_start=497
  _LOADWORKBOOKREQUESTPROTO._serialized_end=537
  _LOADWORKBOOKRESPONSEPROTO._serialized_start=540
  _LOADWORKBOOKRESPONSEPROTO._serialized_end=710
# @@protoc_insertion_point(module_scope)
