# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/emeraldblast/p6/proto/service/CellService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.emeraldblast.p6.proto.service import GetCell_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_service_dot_GetCell__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3com/emeraldblast/p6/proto/service/CellService.proto\x12!com.emeraldblast.p6.proto.service\x1a/com/emeraldblast/p6/proto/service/GetCell.proto2\x86\x01\n\x0b\x43\x65llService\x12w\n\x0cgetCellValue\x12\x31.com.emeraldblast.p6.proto.service.GetCellRequest\x1a\x32.com.emeraldblast.p6.proto.service.GetCellResponse\"\x00\x62\x06proto3')



_CELLSERVICE = DESCRIPTOR.services_by_name['CellService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CELLSERVICE._serialized_start=140
  _CELLSERVICE._serialized_end=274
# @@protoc_insertion_point(module_scope)
