# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/emeraldblast/p6/proto/CommonProtos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,com/emeraldblast/p6/proto/CommonProtos.proto\x12\x19\x63om.emeraldblast.p6.proto\x1a\x1cgoogle/protobuf/struct.proto\"q\n\x10\x45rrorReportProto\x12\x11\n\terrorCode\x18\x01 \x01(\t\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x01(\t\x12\x11\n\x04\x64\x61ta\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x03loc\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_dataB\x06\n\x04_locb\x06proto3')



_ERRORREPORTPROTO = DESCRIPTOR.message_types_by_name['ErrorReportProto']
ErrorReportProto = _reflection.GeneratedProtocolMessageType('ErrorReportProto', (_message.Message,), {
  'DESCRIPTOR' : _ERRORREPORTPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.CommonProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.ErrorReportProto)
  })
_sym_db.RegisterMessage(ErrorReportProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ERRORREPORTPROTO._serialized_start=105
  _ERRORREPORTPROTO._serialized_end=218
# @@protoc_insertion_point(module_scope)
