# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/emeraldblast/p6/proto/ScriptProtos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.emeraldblast.p6.proto import CommonProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_CommonProtos__pb2
from com.emeraldblast.p6.proto import DocProtos_pb2 as com_dot_emeraldblast_dot_p6_dot_proto_dot_DocProtos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,com/emeraldblast/p6/proto/ScriptProtos.proto\x12\x19\x63om.emeraldblast.p6.proto\x1a,com/emeraldblast/p6/proto/CommonProtos.proto\x1a)com/emeraldblast/p6/proto/DocProtos.proto\"z\n\x13ScriptEntryKeyProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x45\n\x0bworkbookKey\x18\x02 \x01(\x0b\x32+.com.emeraldblast.p6.proto.WorkbookKeyProtoH\x00\x88\x01\x01\x42\x0e\n\x0c_workbookKey\"_\n\x10ScriptEntryProto\x12;\n\x03key\x18\x01 \x01(\x0b\x32..com.emeraldblast.p6.proto.ScriptEntryKeyProto\x12\x0e\n\x06script\x18\x02 \x01(\t\"j\n\x18ScriptChangeRequestProto\x12\x11\n\tnewScript\x18\x02 \x01(\t\x12;\n\x03key\x18\x01 \x01(\x0b\x32..com.emeraldblast.p6.proto.ScriptEntryKeyProto\"a\n\x19ScriptChangeResponseProto\x12\x44\n\x0c\x65rrIndicator\x18\x01 \x01(\x0b\x32..com.emeraldblast.p6.proto.ErrorIndicatorProtob\x06proto3')



_SCRIPTENTRYKEYPROTO = DESCRIPTOR.message_types_by_name['ScriptEntryKeyProto']
_SCRIPTENTRYPROTO = DESCRIPTOR.message_types_by_name['ScriptEntryProto']
_SCRIPTCHANGEREQUESTPROTO = DESCRIPTOR.message_types_by_name['ScriptChangeRequestProto']
_SCRIPTCHANGERESPONSEPROTO = DESCRIPTOR.message_types_by_name['ScriptChangeResponseProto']
ScriptEntryKeyProto = _reflection.GeneratedProtocolMessageType('ScriptEntryKeyProto', (_message.Message,), {
  'DESCRIPTOR' : _SCRIPTENTRYKEYPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.ScriptProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.ScriptEntryKeyProto)
  })
_sym_db.RegisterMessage(ScriptEntryKeyProto)

ScriptEntryProto = _reflection.GeneratedProtocolMessageType('ScriptEntryProto', (_message.Message,), {
  'DESCRIPTOR' : _SCRIPTENTRYPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.ScriptProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.ScriptEntryProto)
  })
_sym_db.RegisterMessage(ScriptEntryProto)

ScriptChangeRequestProto = _reflection.GeneratedProtocolMessageType('ScriptChangeRequestProto', (_message.Message,), {
  'DESCRIPTOR' : _SCRIPTCHANGEREQUESTPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.ScriptProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.ScriptChangeRequestProto)
  })
_sym_db.RegisterMessage(ScriptChangeRequestProto)

ScriptChangeResponseProto = _reflection.GeneratedProtocolMessageType('ScriptChangeResponseProto', (_message.Message,), {
  'DESCRIPTOR' : _SCRIPTCHANGERESPONSEPROTO,
  '__module__' : 'com.emeraldblast.p6.proto.ScriptProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.ScriptChangeResponseProto)
  })
_sym_db.RegisterMessage(ScriptChangeResponseProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCRIPTENTRYKEYPROTO._serialized_start=164
  _SCRIPTENTRYKEYPROTO._serialized_end=286
  _SCRIPTENTRYPROTO._serialized_start=288
  _SCRIPTENTRYPROTO._serialized_end=383
  _SCRIPTCHANGEREQUESTPROTO._serialized_start=385
  _SCRIPTCHANGEREQUESTPROTO._serialized_end=491
  _SCRIPTCHANGERESPONSEPROTO._serialized_start=493
  _SCRIPTCHANGERESPONSEPROTO._serialized_end=590
# @@protoc_insertion_point(module_scope)
