# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DocProtos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import CommonProtos_pb2 as CommonProtos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x44ocProtos.proto\x12\x19\x63om.emeraldblast.p6.proto\x1a\x12\x43ommonProtos.proto\",\n\x10\x43\x65llAddressProto\x12\x0b\n\x03\x63ol\x18\x01 \x01(\x05\x12\x0b\n\x03row\x18\x02 \x01(\x05\"\x80\x01\n\tCellProto\x12\x14\n\x0c\x64isplayValue\x18\x01 \x01(\t\x12\x0f\n\x07\x66ormula\x18\x02 \x01(\t\x12\x0e\n\x06script\x18\x03 \x01(\t\x12<\n\x07\x61\x64\x64ress\x18\x04 \x01(\x0b\x32+.com.emeraldblast.p6.proto.CellAddressProto\"R\n\x0eWorksheetProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x32\n\x04\x63\x65ll\x18\x02 \x03(\x0b\x32$.com.emeraldblast.p6.proto.CellProto\"Y\n\x10WorkbookKeyProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x37\n\x04path\x18\x02 \x01(\x0b\x32).com.emeraldblast.p6.proto.NullableString\"\x8f\x01\n\rWorkbookProto\x12@\n\x0bworkbookKey\x18\x01 \x01(\x0b\x32+.com.emeraldblast.p6.proto.WorkbookKeyProto\x12<\n\tworksheet\x18\x02 \x03(\x0b\x32).com.emeraldblast.p6.proto.WorksheetProtob\x06proto3')



_CELLADDRESSPROTO = DESCRIPTOR.message_types_by_name['CellAddressProto']
_CELLPROTO = DESCRIPTOR.message_types_by_name['CellProto']
_WORKSHEETPROTO = DESCRIPTOR.message_types_by_name['WorksheetProto']
_WORKBOOKKEYPROTO = DESCRIPTOR.message_types_by_name['WorkbookKeyProto']
_WORKBOOKPROTO = DESCRIPTOR.message_types_by_name['WorkbookProto']
CellAddressProto = _reflection.GeneratedProtocolMessageType('CellAddressProto', (_message.Message,), {
  'DESCRIPTOR' : _CELLADDRESSPROTO,
  '__module__' : 'DocProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.CellAddressProto)
  })
_sym_db.RegisterMessage(CellAddressProto)

CellProto = _reflection.GeneratedProtocolMessageType('CellProto', (_message.Message,), {
  'DESCRIPTOR' : _CELLPROTO,
  '__module__' : 'DocProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.CellProto)
  })
_sym_db.RegisterMessage(CellProto)

WorksheetProto = _reflection.GeneratedProtocolMessageType('WorksheetProto', (_message.Message,), {
  'DESCRIPTOR' : _WORKSHEETPROTO,
  '__module__' : 'DocProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.WorksheetProto)
  })
_sym_db.RegisterMessage(WorksheetProto)

WorkbookKeyProto = _reflection.GeneratedProtocolMessageType('WorkbookKeyProto', (_message.Message,), {
  'DESCRIPTOR' : _WORKBOOKKEYPROTO,
  '__module__' : 'DocProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.WorkbookKeyProto)
  })
_sym_db.RegisterMessage(WorkbookKeyProto)

WorkbookProto = _reflection.GeneratedProtocolMessageType('WorkbookProto', (_message.Message,), {
  'DESCRIPTOR' : _WORKBOOKPROTO,
  '__module__' : 'DocProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.WorkbookProto)
  })
_sym_db.RegisterMessage(WorkbookProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CELLADDRESSPROTO._serialized_start=66
  _CELLADDRESSPROTO._serialized_end=110
  _CELLPROTO._serialized_start=113
  _CELLPROTO._serialized_end=241
  _WORKSHEETPROTO._serialized_start=243
  _WORKSHEETPROTO._serialized_end=325
  _WORKBOOKKEYPROTO._serialized_start=327
  _WORKBOOKKEYPROTO._serialized_end=416
  _WORKBOOKPROTO._serialized_start=419
  _WORKBOOKPROTO._serialized_end=562
# @@protoc_insertion_point(module_scope)
