# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WorkbookProtos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import CommonProtos_pb2 as CommonProtos__pb2
from . import DocProtos_pb2 as DocProtos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14WorkbookProtos.proto\x12\x19\x63om.emeraldblast.p6.proto\x1a\x12\x43ommonProtos.proto\x1a\x0f\x44ocProtos.proto\"|\n\x1e\x43reateNewWorksheetRequestProto\x12@\n\x0bworkbookKey\x18\x01 \x01(\x0b\x32+.com.emeraldblast.p6.proto.WorkbookKeyProto\x12\x18\n\x10newWorksheetName\x18\x02 \x01(\t\"\xd0\x01\n\x1f\x43reateNewWorksheetResponseProto\x12@\n\x0bworkbookKey\x18\x01 \x01(\x0b\x32+.com.emeraldblast.p6.proto.WorkbookKeyProto\x12\x18\n\x10newWorksheetName\x18\x02 \x01(\t\x12\x0f\n\x07isError\x18\x03 \x01(\x08\x12@\n\x0b\x65rrorReport\x18\x04 \x01(\x0b\x32+.com.emeraldblast.p6.proto.ErrorReportProtob\x06proto3')



_CREATENEWWORKSHEETREQUESTPROTO = DESCRIPTOR.message_types_by_name['CreateNewWorksheetRequestProto']
_CREATENEWWORKSHEETRESPONSEPROTO = DESCRIPTOR.message_types_by_name['CreateNewWorksheetResponseProto']
CreateNewWorksheetRequestProto = _reflection.GeneratedProtocolMessageType('CreateNewWorksheetRequestProto', (_message.Message,), {
  'DESCRIPTOR' : _CREATENEWWORKSHEETREQUESTPROTO,
  '__module__' : 'WorkbookProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.CreateNewWorksheetRequestProto)
  })
_sym_db.RegisterMessage(CreateNewWorksheetRequestProto)

CreateNewWorksheetResponseProto = _reflection.GeneratedProtocolMessageType('CreateNewWorksheetResponseProto', (_message.Message,), {
  'DESCRIPTOR' : _CREATENEWWORKSHEETRESPONSEPROTO,
  '__module__' : 'WorkbookProtos_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.CreateNewWorksheetResponseProto)
  })
_sym_db.RegisterMessage(CreateNewWorksheetResponseProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATENEWWORKSHEETREQUESTPROTO._serialized_start=88
  _CREATENEWWORKSHEETREQUESTPROTO._serialized_end=212
  _CREATENEWWORKSHEETRESPONSEPROTO._serialized_start=215
  _CREATENEWWORKSHEETRESPONSEPROTO._serialized_end=423
# @@protoc_insertion_point(module_scope)
