# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WorkbookProtoMsg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Common_pb2 as Common__pb2
from . import DocProto_pb2 as DocProto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16WorkbookProtoMsg.proto\x12\x19\x63om.emeraldblast.p6.proto\x1a\x0c\x43ommon.proto\x1a\x0e\x44ocProto.proto\"|\n\x1e\x43reateNewWorksheetRequestProto\x12@\n\x0bworkbookKey\x18\x01 \x01(\x0b\x32+.com.emeraldblast.p6.proto.WorkbookKeyProto\x12\x18\n\x10newWorksheetName\x18\x02 \x01(\t\"\xc8\x01\n\x17\x43reateNewWorksheetProto\x12@\n\x0bworkbookKey\x18\x01 \x01(\x0b\x32+.com.emeraldblast.p6.proto.WorkbookKeyProto\x12\x18\n\x10newWorksheetName\x18\x02 \x01(\t\x12\x0f\n\x07isError\x18\x03 \x01(\x08\x12@\n\x0b\x65rrorReport\x18\x04 \x01(\x0b\x32+.com.emeraldblast.p6.proto.ErrorReportProtob\x06proto3')



_CREATENEWWORKSHEETREQUESTPROTO = DESCRIPTOR.message_types_by_name['CreateNewWorksheetRequestProto']
_CREATENEWWORKSHEETPROTO = DESCRIPTOR.message_types_by_name['CreateNewWorksheetProto']
CreateNewWorksheetRequestProto = _reflection.GeneratedProtocolMessageType('CreateNewWorksheetRequestProto', (_message.Message,), {
  'DESCRIPTOR' : _CREATENEWWORKSHEETREQUESTPROTO,
  '__module__' : 'WorkbookProtoMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.CreateNewWorksheetRequestProto)
  })
_sym_db.RegisterMessage(CreateNewWorksheetRequestProto)

CreateNewWorksheetProto = _reflection.GeneratedProtocolMessageType('CreateNewWorksheetProto', (_message.Message,), {
  'DESCRIPTOR' : _CREATENEWWORKSHEETPROTO,
  '__module__' : 'WorkbookProtoMsg_pb2'
  # @@protoc_insertion_point(class_scope:com.emeraldblast.p6.proto.CreateNewWorksheetProto)
  })
_sym_db.RegisterMessage(CreateNewWorksheetProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATENEWWORKSHEETREQUESTPROTO._serialized_start=83
  _CREATENEWWORKSHEETREQUESTPROTO._serialized_end=207
  _CREATENEWWORKSHEETPROTO._serialized_start=210
  _CREATENEWWORKSHEETPROTO._serialized_end=410
# @@protoc_insertion_point(module_scope)
