# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x43ommon.proto\x12\x1d\x63om.github.xadkile.p6.app.msg\x1a\x1cgoogle/protobuf/struct.proto\"S\n\x0eNullableString\x12*\n\x04null\x18\x01 \x01(\x0e\x32\x1a.google.protobuf.NullValueH\x00\x12\r\n\x03str\x18\x02 \x01(\tH\x00\x42\x06\n\x04kindb\x06proto3')



_NULLABLESTRING = DESCRIPTOR.message_types_by_name['NullableString']
NullableString = _reflection.GeneratedProtocolMessageType('NullableString', (_message.Message,), {
  'DESCRIPTOR' : _NULLABLESTRING,
  '__module__' : 'Common_pb2'
  # @@protoc_insertion_point(class_scope:com.github.xadkile.p6.app.msg.NullableString)
  })
_sym_db.RegisterMessage(NullableString)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NULLABLESTRING._serialized_start=77
  _NULLABLESTRING._serialized_end=160
# @@protoc_insertion_point(module_scope)
