# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: P6MsgPM.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rP6MsgPM.proto\x12$com.github.xadkile.message.api.proto\"8\n\x14P6MessageHeaderProto\x12\r\n\x05msgId\x18\x01 \x01(\t\x12\x11\n\teventType\x18\x02 \x01(\t\"j\n\x0eP6MessageProto\x12J\n\x06header\x18\x01 \x01(\x0b\x32:.com.github.xadkile.message.api.proto.P6MessageHeaderProto\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\tb\x06proto3')



_P6MESSAGEHEADERPROTO = DESCRIPTOR.message_types_by_name['P6MessageHeaderProto']
_P6MESSAGEPROTO = DESCRIPTOR.message_types_by_name['P6MessageProto']
P6MessageHeaderProto = _reflection.GeneratedProtocolMessageType('P6MessageHeaderProto', (_message.Message,), {
  'DESCRIPTOR' : _P6MESSAGEHEADERPROTO,
  '__module__' : 'P6MsgPM_pb2'
  # @@protoc_insertion_point(class_scope:com.github.xadkile.message.api.proto.P6MessageHeaderProto)
  })
_sym_db.RegisterMessage(P6MessageHeaderProto)

P6MessageProto = _reflection.GeneratedProtocolMessageType('P6MessageProto', (_message.Message,), {
  'DESCRIPTOR' : _P6MESSAGEPROTO,
  '__module__' : 'P6MsgPM_pb2'
  # @@protoc_insertion_point(class_scope:com.github.xadkile.message.api.proto.P6MessageProto)
  })
_sym_db.RegisterMessage(P6MessageProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _P6MESSAGEHEADERPROTO._serialized_start=55
  _P6MESSAGEHEADERPROTO._serialized_end=111
  _P6MESSAGEPROTO._serialized_start=113
  _P6MESSAGEPROTO._serialized_end=219
# @@protoc_insertion_point(module_scope)
