# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/qxdzbc/p6/proto/rpc/worksheet/service/WorksheetService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.qxdzbc.p6.proto import CommonProtos_pb2 as com_dot_qxdzbc_dot_p6_dot_proto_dot_CommonProtos__pb2
from com.qxdzbc.p6.proto import DocProtos_pb2 as com_dot_qxdzbc_dot_p6_dot_proto_dot_DocProtos__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from com.qxdzbc.p6.proto.rpc.worksheet import WorksheetServiceProtos_pb2 as com_dot_qxdzbc_dot_p6_dot_proto_dot_rpc_dot_worksheet_dot_WorksheetServiceProtos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@com/qxdzbc/p6/proto/rpc/worksheet/service/WorksheetService.proto\x12)com.qxdzbc.p6.proto.rpc.worksheet.service\x1a&com/qxdzbc/p6/proto/CommonProtos.proto\x1a#com/qxdzbc/p6/proto/DocProtos.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a>com/qxdzbc/p6/proto/rpc/worksheet/WorksheetServiceProtos.proto2q\n\x10WorksheetService\x12]\n\x07getCell\x12 .com.qxdzbc.p6.proto.CellIdProto\x1a..com.qxdzbc.p6.proto.SingleSignalResponseProto\"\x00')



_WORKSHEETSERVICE = DESCRIPTOR.services_by_name['WorksheetService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORKSHEETSERVICE._serialized_start=313
  _WORKSHEETSERVICE._serialized_end=426
# @@protoc_insertion_point(module_scope)
